tumblr:
  key: "eQMOLI2PSPJ5hVBGkfGXdscYhmgszQdRFCul5ehxWP2GcC64bp"
  secret: "XwDAtLUQJmKYhTmJtV9si2FL38TCLMQ5YShlitCdKeepG7U4at"
twitter:
  key: "SdwKtY80hD2fphQuYLAuA"
  secret: "BnFNC4gDwc0t62pcs9vU5n3EoFgpp97KUpeue2EC9CA"
facebook:
  key: "219931781462840"
  secret: "a5718154303bce56b74af5f5b7b335a3"